included: # paths to include during linting. `--path` is ignored if present.
  - PhotoGridApp
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
line_length:
  warning: 400
  error: 500
identifier_name:
  min_length: 2 # only min_length