# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoGridApp' do
  pod 'Alamofire'
  pod 'Sniffer'

  target 'PhotoGridAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoGridAppUITests' do
    # Pods for testing
  end

end